backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

# Medya klasörü hatasını çözmek için:
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "notlar"
    label: "Notlar"
    folder: "content/docs" # Kök dizin
    extension: "md"
    format: "frontmatter"
    create: true
    # ALT KLASÖR DESTEĞİ BURADA:
    path: "{{dirname}}/{{slug}}"
    slug: "{{slug}}"
    filter:
      field: "title"
      value: ".*" # Başlığı olan her şeyi getir
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "İçerik", name: "body", widget: "markdown"}
      - {label: "Sıralama (Weight)", name: "weight", widget: "number", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
